# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lin.core.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('abstract', models.CharField(max_length=512, null=True)),
                ('date', models.DateTimeField(db_column='create_date')),
                ('modifyDate', models.DateTimeField(db_column='modify_date')),
                ('content', models.TextField(max_length=8192)),
                ('show', models.BooleanField(db_column='is_show', default=False)),
                ('browse', models.IntegerField(db_column='browse_count', default=0)),
                ('userId', models.CharField(db_column='user_id', max_length=40)),
                ('userName', models.CharField(db_column='user_name', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date', models.DateTimeField(db_column='create_date')),
                ('modifyDate', models.DateTimeField(db_column='modify_date')),
                ('show', models.BooleanField(db_column='is_show', default=False)),
                ('order', models.IntegerField()),
                ('type', models.IntegerField(db_column='node_type', default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_items', to='web.ArticleClass')),
            ],
            bases=(models.Model, lin.core.models.Model),
        ),
        migrations.AddField(
            model_name='article',
            name='article_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_id', to='web.ArticleClass'),
        ),
    ]
