# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='asv_article',
        ),
        migrations.AlterModelTable(
            name='articleclass',
            table='asv_article_class',
        ),
    ]
