# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20160613_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isDelete',
            field=models.BooleanField(db_column='is_delete', default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.IntegerField(db_column='article_type', default=0),
        ),
        migrations.AddField(
            model_name='articleclass',
            name='code',
            field=models.CharField(db_column='article_code', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='articleclass',
            name='isDelete',
            field=models.BooleanField(db_column='is_delete', default=False),
        ),
        migrations.AddField(
            model_name='articleclass',
            name='own',
            field=models.CharField(db_column='article_own', max_length=32, null=True),
        ),
    ]
