# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160615_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleclass',
            name='desc',
            field=models.CharField(db_column='class_desc', max_length=256, null=True),
        ),
    ]
