# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_column='user_name', max_length=64)),
                ('nickname', models.CharField(db_column='nick_name', max_length=64)),
                ('password', models.CharField(db_column='password', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(db_column='permission_desc', max_length=255)),
                ('url', models.CharField(db_column='url_str', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='role_name', max_length=64)),
                ('desc', models.CharField(db_column='role_desc', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RolePermissInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(db_column='state_date', null=True)),
                ('endDate', models.DateTimeField(db_column='end_data', null=True)),
                ('desc', models.CharField(db_column='desc', max_length=255)),
                ('permisses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permiss_id', to='auth.Permission')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_id', to='auth.Role')),
            ],
        ),
        migrations.CreateModel(
            name='UserBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcent', models.FloatField(db_column='parcent', default=0.7)),
            ],
        ),
        migrations.CreateModel(
            name='UserPermissInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(db_column='state_date', null=True)),
                ('endDate', models.DateTimeField(db_column='end_data', null=True)),
                ('desc', models.CharField(db_column='desc', max_length=255)),
                ('permisses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permiss_id', to='auth.Role')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='auth.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserRoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField(db_column='state_date', null=True)),
                ('endDate', models.DateTimeField(db_column='end_data', null=True)),
                ('desc', models.CharField(db_column='desc', max_length=255)),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_id', to='auth.Permission')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='auth.Role')),
            ],
        ),
    ]
