# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-13 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='asv_user_permission',
        ),
        migrations.AlterModelTable(
            name='role',
            table='asv_user_role',
        ),
        migrations.AlterModelTable(
            name='rolepermissinfo',
            table='asv_user_role_permiss_info',
        ),
        migrations.AlterModelTable(
            name='user',
            table='asv_user',
        ),
        migrations.AlterModelTable(
            name='userbaseinfo',
            table='asv_user_base_info',
        ),
        migrations.AlterModelTable(
            name='userpermissinfo',
            table='asv_user_permission_info',
        ),
        migrations.AlterModelTable(
            name='userroleinfo',
            table='asv_user_role_info',
        ),
    ]
