# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_auto_20160613_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isDelete',
            field=models.BooleanField(db_column='is_delete', default=False),
        ),
    ]
